version: '3'


tasks:
  sync:
    desc: Setup project with dependencies
    dir: code-confluence-flow-bridge
    cmds:
      - uv sync

  run-dev:
    desc: Run FastAPI application in development mode
    deps: [sync]
    dir: code-confluence-flow-bridge/src/code_confluence_flow_bridge
    cmds:
      - uv run fastapi dev

  dev:
    desc: Install dependencies and run the application
    cmds:
      - task: run-dev

  test:
    desc: Run tests
    dir: code-confluence-flow-bridge
    cmds:
      - uv run pytest tests/ -v 
