from __future__ import annotations

from typing import Protocol


class DockerComposeManager(Protocol):
    def ensure_available(self) -> None: ...
    def pull_images(self) -> None: ...
    def start_stack(self) -> None: ...
    def stop_stack(self, *, volumes: bool) -> None: ...
