/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as SettingsToolConfigRouteImport } from './routes/settings.tool-config'
import { Route as SettingsModelProvidersRouteImport } from './routes/settings.model-providers'
import { Route as SettingsDeveloperRouteImport } from './routes/settings.developer'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRepositoryOperationsRouteImport } from './routes/_app.repositoryOperations'
import { Route as AppOperationsManagementRouteImport } from './routes/_app.operationsManagement'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppDeveloperRouteImport } from './routes/_app.developer'
import { Route as AppOnboardingIndexRouteImport } from './routes/_app.onboarding.index'
import { Route as AppOnboardingProviderRouteImport } from './routes/_app.onboarding.$provider'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SettingsToolConfigRoute = SettingsToolConfigRouteImport.update({
  id: '/settings/tool-config',
  path: '/settings/tool-config',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsModelProvidersRoute = SettingsModelProvidersRouteImport.update({
  id: '/settings/model-providers',
  path: '/settings/model-providers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDeveloperRoute = SettingsDeveloperRouteImport.update({
  id: '/settings/developer',
  path: '/settings/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositoryOperationsRoute = AppRepositoryOperationsRouteImport.update({
  id: '/repositoryOperations',
  path: '/repositoryOperations',
  getParentRoute: () => AppRoute,
} as any)
const AppOperationsManagementRoute = AppOperationsManagementRouteImport.update({
  id: '/operationsManagement',
  path: '/operationsManagement',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppDeveloperRoute = AppDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingIndexRoute = AppOnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOnboardingRoute,
} as any)
const AppOnboardingProviderRoute = AppOnboardingProviderRouteImport.update({
  id: '/$provider',
  path: '/$provider',
  getParentRoute: () => AppOnboardingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/developer': typeof AppDeveloperRoute
  '/onboarding': typeof AppOnboardingRouteWithChildren
  '/operationsManagement': typeof AppOperationsManagementRoute
  '/repositoryOperations': typeof AppRepositoryOperationsRoute
  '/settings': typeof AppSettingsRoute
  '/settings/developer': typeof SettingsDeveloperRoute
  '/settings/model-providers': typeof SettingsModelProvidersRoute
  '/settings/tool-config': typeof SettingsToolConfigRoute
  '/': typeof AppIndexRoute
  '/onboarding/$provider': typeof AppOnboardingProviderRoute
  '/onboarding/': typeof AppOnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/developer': typeof AppDeveloperRoute
  '/operationsManagement': typeof AppOperationsManagementRoute
  '/repositoryOperations': typeof AppRepositoryOperationsRoute
  '/settings': typeof AppSettingsRoute
  '/settings/developer': typeof SettingsDeveloperRoute
  '/settings/model-providers': typeof SettingsModelProvidersRoute
  '/settings/tool-config': typeof SettingsToolConfigRoute
  '/': typeof AppIndexRoute
  '/onboarding/$provider': typeof AppOnboardingProviderRoute
  '/onboarding': typeof AppOnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/developer': typeof AppDeveloperRoute
  '/_app/onboarding': typeof AppOnboardingRouteWithChildren
  '/_app/operationsManagement': typeof AppOperationsManagementRoute
  '/_app/repositoryOperations': typeof AppRepositoryOperationsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/settings/developer': typeof SettingsDeveloperRoute
  '/settings/model-providers': typeof SettingsModelProvidersRoute
  '/settings/tool-config': typeof SettingsToolConfigRoute
  '/_app/': typeof AppIndexRoute
  '/_app/onboarding/$provider': typeof AppOnboardingProviderRoute
  '/_app/onboarding/': typeof AppOnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/developer'
    | '/onboarding'
    | '/operationsManagement'
    | '/repositoryOperations'
    | '/settings'
    | '/settings/developer'
    | '/settings/model-providers'
    | '/settings/tool-config'
    | '/'
    | '/onboarding/$provider'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/developer'
    | '/operationsManagement'
    | '/repositoryOperations'
    | '/settings'
    | '/settings/developer'
    | '/settings/model-providers'
    | '/settings/tool-config'
    | '/'
    | '/onboarding/$provider'
    | '/onboarding'
  id:
    | '__root__'
    | '/_app'
    | '/_app/developer'
    | '/_app/onboarding'
    | '/_app/operationsManagement'
    | '/_app/repositoryOperations'
    | '/_app/settings'
    | '/settings/developer'
    | '/settings/model-providers'
    | '/settings/tool-config'
    | '/_app/'
    | '/_app/onboarding/$provider'
    | '/_app/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SettingsDeveloperRoute: typeof SettingsDeveloperRoute
  SettingsModelProvidersRoute: typeof SettingsModelProvidersRoute
  SettingsToolConfigRoute: typeof SettingsToolConfigRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/settings/tool-config': {
      id: '/settings/tool-config'
      path: '/settings/tool-config'
      fullPath: '/settings/tool-config'
      preLoaderRoute: typeof SettingsToolConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/model-providers': {
      id: '/settings/model-providers'
      path: '/settings/model-providers'
      fullPath: '/settings/model-providers'
      preLoaderRoute: typeof SettingsModelProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/developer': {
      id: '/settings/developer'
      path: '/settings/developer'
      fullPath: '/settings/developer'
      preLoaderRoute: typeof SettingsDeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repositoryOperations': {
      id: '/_app/repositoryOperations'
      path: '/repositoryOperations'
      fullPath: '/repositoryOperations'
      preLoaderRoute: typeof AppRepositoryOperationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operationsManagement': {
      id: '/_app/operationsManagement'
      path: '/operationsManagement'
      fullPath: '/operationsManagement'
      preLoaderRoute: typeof AppOperationsManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developer': {
      id: '/_app/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof AppDeveloperRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding/': {
      id: '/_app/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AppOnboardingIndexRouteImport
      parentRoute: typeof AppOnboardingRoute
    }
    '/_app/onboarding/$provider': {
      id: '/_app/onboarding/$provider'
      path: '/$provider'
      fullPath: '/onboarding/$provider'
      preLoaderRoute: typeof AppOnboardingProviderRouteImport
      parentRoute: typeof AppOnboardingRoute
    }
  }
}

interface AppOnboardingRouteChildren {
  AppOnboardingProviderRoute: typeof AppOnboardingProviderRoute
  AppOnboardingIndexRoute: typeof AppOnboardingIndexRoute
}

const AppOnboardingRouteChildren: AppOnboardingRouteChildren = {
  AppOnboardingProviderRoute: AppOnboardingProviderRoute,
  AppOnboardingIndexRoute: AppOnboardingIndexRoute,
}

const AppOnboardingRouteWithChildren = AppOnboardingRoute._addFileChildren(
  AppOnboardingRouteChildren,
)

interface AppRouteChildren {
  AppDeveloperRoute: typeof AppDeveloperRoute
  AppOnboardingRoute: typeof AppOnboardingRouteWithChildren
  AppOperationsManagementRoute: typeof AppOperationsManagementRoute
  AppRepositoryOperationsRoute: typeof AppRepositoryOperationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDeveloperRoute: AppDeveloperRoute,
  AppOnboardingRoute: AppOnboardingRouteWithChildren,
  AppOperationsManagementRoute: AppOperationsManagementRoute,
  AppRepositoryOperationsRoute: AppRepositoryOperationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SettingsDeveloperRoute: SettingsDeveloperRoute,
  SettingsModelProvidersRoute: SettingsModelProvidersRoute,
  SettingsToolConfigRoute: SettingsToolConfigRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
