# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  install:
    desc: Install dependencies using yarn
    cmds:
      - bun install
    # Only run if package.json or yarn.lock have changed
    sources:
      - package.json
      - bun.json

  build:
    desc: Build the application
    deps: [install]
    cmds:
      - vite build
    sources:
      - src/**/*
      - public/**/*
      - index.html
      - vite.config.ts
    generates:
      - dist/**/*

  dev:
    desc: Start development environment
    deps: [install]
    cmds:
      - vite

  lint:
    desc: do linitng using eslint
    cmds:
      - bun eslint .

  lint-fix:
    desc: fix linitng using eslint
    cmds:
      - bun eslint . --fix

  format:
    desc: Format all files using Prettier
    cmds:
      - bun prettier --write .

  format-check:
    desc: Check if files are formatted without modifying them
    cmds:
      - bun prettier --check .

  docker:
    desc: Build and run docker container locally
    deps: [build]
    cmds:
      - docker build -t vite-app .
      - docker run -p 3000:80 vite-app

  outdated:
    desc: Review outdated packages and check for available updates
    cmds:
      - bun outdated
