# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  install:
    desc: Install dependencies using yarn
    cmds:
      - bun install
    # Only run if package.json or yarn.lock have changed
    sources:
      - package.json
      - bun.json

  build:
    desc: Build the application
    deps: [install]
    cmds:
      - vite build
    sources:
      - src/**/*
      - public/**/*
      - index.html
      - vite.config.ts
    generates:
      - dist/**/*

  dev:
    desc: Start development environment
    deps: [install]
    cmds:
      - vite

  lint:
    desc: "Lint files (optional: FILE_PATH=src/path/to/file.tsx)"
    cmds:
      - bun eslint {{.FILE_PATH | default "."}}
    vars:
      FILE_PATH: ""

  lint-fix:
    desc: "Lint and fix files (optional: FILE_PATH=src/path/to/file.tsx)"
    cmds:
      - bun eslint {{.FILE_PATH | default "."}} --fix
    vars:
      FILE_PATH: ""

  format:
    desc: "Format files with Prettier (optional: FILE_PATH=src/path/to/file.tsx)"
    cmds:
      - bun prettier --write {{.FILE_PATH | default "."}}
    vars:
      FILE_PATH: ""

  format-check:
    desc: "Check formatting without modifying (optional: FILE_PATH=src/path/to/file.tsx)"
    cmds:
      - bun prettier --check {{.FILE_PATH | default "."}}
    vars:
      FILE_PATH: ""

  docker:
    desc: Build and run docker container locally
    deps: [build]
    cmds:
      - docker build -t vite-app .
      - docker run -p 3000:80 vite-app

  outdated:
    desc: Review outdated packages and check for available updates
    cmds:
      - bun outdated
