# Target Python 3.10
target-version = "py311"

exclude = [
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "venv",
    "build",
    "dist",
    "tests"
]

src = ["src/code_confluence_flow_bridge"]  # Adjust this to your project's source directory
line-length = 150

[lint]
preview = true
select = ["I","E402","INP001","TID","F401","F841","PLC0415"]

[lint.per-file-ignores]
"__init__.py" = ["E402","F401"]

[lint.flake8-tidy-imports]
ban-relative-imports = "all"

[lint.isort]
force-to-top = ["os","sys"]
force-sort-within-sections = true
combine-as-imports = true
from-first = true
section-order = ["future","first-party", "local-folder", "standard-library", "third-party"]
lines-between-types = 2



