version: "3"

tasks:
  check-temporal-port:
    cmds:
      - |
        if ! lsof -i:8080 > /dev/null 2>&1; then
          echo "Port 8080 is available"
          exit 0
        else
          echo "Port 8080 is already in use"
          exit 1
        fi
    silent: true

  start-temporal:
    deps: [check-temporal-port]
    cmds:
      # Run temporal server in background using &
      - temporal server start-dev --ui-port 8080

  start-neo4j:
    cmds:
      - docker run 
          -p7474:7474 -p7687:7687 
          -v "$HOME/neo4j/data:/data" 
          -v "$HOME/neo4j/logs:/logs" 
          -v "$HOME/neo4j/import:/var/lib/neo4j/import" 
          -v "$HOME/neo4j/plugins:/plugins" 
          --env NEO4J_AUTH=neo4j/password 
          --env NEO4J_PLUGINS='["apoc"]' 
          --env NEO4J_apoc_export_file_enabled=true 
          --env NEO4J_apoc_import_file_enabled=true 
          --env NEO4J_dbms_security_procedures_unrestricted='*' 
          graphstack/dozerdb:5.25.1.0-alpha.1

  start-dependencies:
    desc: Start all dependencies using docker-compose
    cmds:
      - docker-compose -f local-dependencies-only-docker-compose.yml up -d
      - echo "Waiting for services to be ready..."
      - sleep 10  # Add a brief wait for services to initialize

  stop-dependencies:
    desc: Stop all dependencies and remove volumes
    cmds:
      - docker-compose -f local-dependencies-only-docker-compose.yml down --volumes

  sync:
    desc: Setup project with dependencies
    dir: .
    cmds:
      - uv sync

  update-package:
    desc: Update a specific package to the latest allowed version using uv (usage - task update-package PACKAGE=package_name)
    vars:
      PACKAGE: '{{.PACKAGE}}'
    requires:
      vars: [PACKAGE]
    cmds:
      - uv lock --upgrade-package {{.PACKAGE}}

  update-all-packages:
    desc: Update all packages to the latest allowed versions using uv
    cmds:
      - uv lock --upgrade

  run-client:
    desc: run client to submit request to code confluence flow code-confluence-flow-bridge
    dir: ../../unoplat-code-confluence-cli
    cmds:
      - uv run unoplat_code_confluence_cli --config example_config_code_confluence_current.json

  run-dev:
    desc: Run FastAPI application in development mode
    deps: [sync]
    dir: src/code_confluence_flow_bridge
    env:
      DB_HOST: "localhost"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "code_confluence"
      NEO4J_HOST: "localhost"
      NEO4J_PORT: "7687"
      NEO4J_USERNAME: "neo4j"
      NEO4J_PASSWORD: "password"
      TEMPORAL_SERVER_ADDRESS: "localhost:7233"
      OTEL_EXPORTER_OTLP_ENDPOINT: "localhost:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "code-confluence-flow-bridge"
      OTEL_PROPAGATORS: "tracecontext,baggage"
      FRAMEWORK_DEFINITIONS_PATH: "../../framework-definitions"
    cmds:
      - uv run fastapi dev

  dev:
    desc: Install dependencies, start required services, and run the application
    cmds:
      - task: start-dependencies
      - task: run-dev

  test:
    desc: Run tests with coverage
    dir: .
    cmds:
      # Sync only the test dependencies group before running tests.
      - uv sync --group test
      - uv run --python 3.13 --group test pytest --cov=src/code_confluence_flow_bridge --cov-report=html:coverage_reports tests/ -v
      - task: stop-dependencies

  ci-test:
    desc: Run tests in CI mode using act command with additional environment variable
    dir: ../../
    env:
      DOCKER_HOST: "unix:///{{.HOME}}/.orbstack/run/docker.sock"
    cmds:
      - act pull_request_target -j test-uv-projects -s GITHUB_TOKEN="$(gh auth token)" --env GITHUB_REPOSITORY="unoplat/unoplat-code-confluence" --env GITHUB_HEAD_REF="end-end-test-local-temporal-workflow" --env GITHUB_BASE_REF="main" --local-repository="." --container-architecture linux/amd64 -P ubuntu-latest=catthehacker/ubuntu:act-latest

  run-github-action-locally:
    desc: Run GitHub Actions python_build workflow locally using act
    dir: ../../
    cmds:
      - |
        act pull_request_target -j test-uv-projects \
          -s GITHUB_TOKEN="$(gh auth token)" \
          --env GITHUB_REPOSITORY="unoplat/unoplat-code-confluence" \
          --env GITHUB_HEAD_REF="fix-docker-compose" \
          --env GITHUB_BASE_REF="main" \
          --local-repository="." \
          --container-architecture linux/arm64 \
          -P ubuntu-latest=catthehacker/ubuntu:act-latest

  lint:
    desc: Run ruff linter on the codebase
    dir: .
    cmds:
      - uv run ruff check src/

  lint-fix:
    desc: Run ruff linter and auto-fix issues
    dir: .
    cmds:
      - uv run ruff check src/ --fix

  typecheck:
    desc: Run mypy type checker on the codebase
    dir: .
    cmds:
      - uv run mypy src/

  format:
    desc: Format code using ruff
    dir: .
    cmds:
      - uv run ruff format src/

  validate-framework-definitions:
    desc: Validate all framework definition JSON files against schema
    dir: .
    cmds:
      - uv run --group dev check-jsonschema --schemafile framework-definitions/schema.json framework-definitions/python/*.json

  validate-single-framework:
    desc: Validate a specific framework definition (usage - task validate-single-framework FILE=framework-definitions/python/fastapi.json)
    vars:
      FILE: '{{.FILE}}'
    requires:
      vars: [FILE]
    cmds:
      - uv run --group dev check-jsonschema --schemafile framework-definitions/schema.json {{.FILE}}

  validate-all:
    desc: Run all validation checks (framework definitions + code quality)
    cmds:
      - task: validate-framework-definitions
      - task: code-quality

  code-quality:
    desc: Run all code quality checks (lint, typecheck, schema validation)
    dir: .
    cmds:
      - task: lint
      - task: typecheck
      - task: validate-framework-definitions

  find-pytest-errors:
    desc: Diagnose pytest test discovery issues and import errors
    dir: .
    cmds:
     - uv run --group test pytest --collect-only tests
     