from unoplat_code_confluence.language_custom_parsing.python.package_manager.package_manager_strategy import PackageManagerStrategy
from unoplat_code_confluence.configuration.external_config import ProgrammingLanguageMetadata
from unoplat_code_confluence.data_models.unoplat_package_manager_metadata import UnoplatPackageManagerMetadata

class PipStrategy(PackageManagerStrategy):
    def process_metadata(self, local_workspace_path: str, metadata: ProgrammingLanguageMetadata) -> UnoplatPackageManagerMetadata: