"""Shared logger protocol for request-scoped logging dependencies."""

from typing import Protocol


class StructuredLogger(Protocol):
    """Minimal logger surface used by request-scoped workflow helpers."""

    def debug(self, message: str, *args: object, **kwargs: object) -> None: ...
    def info(self, message: str, *args: object, **kwargs: object) -> None: ...
    def warning(self, message: str, *args: object, **kwargs: object) -> None: ...
    def error(self, message: str, *args: object, **kwargs: object) -> None: ...
