version: '3'

tasks:
  install:
    desc: Install dependencies with uv
    cmds:
      - uv sync

  test:
    desc: Run pytest through uv
    deps: [install]
    cmds:
      - uv run pytest -v tests/

  test:watch:
    desc: Run pytest in watch mode
    deps: [install]
    cmds:
      - uv run pytest -v -f tests/

  all:
    desc: Run all checks (install, test)
    cmds:
      - task: install
      - task: test
