name: Promote App Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  app-release:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'dev'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Release Please (app bundle)
        id: release_app
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.PAT }}
          config-file: .github/configuration/release-please-app-config.json
          manifest-file: .github/configuration/release-please-app-manifest.json
          include-component-in-tag: true
          target-branch: main
