name: unoplat_code_confluence_discord

on:
  release:
    types: [published]   # fires only when a release is published

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send nicely-formatted embed to Discord
        uses: SethCohen/github-releases-to-discord@v1
        with:
          webhook_url: ${{ secrets.DISCORD_UNOPLAT_CODE_CONFLUENCE_WEBHOOK }}