name: Develop Branch Action
on:
  pull_request_target:
    types: 
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths:
      - 'unoplat-code-confluence-commons/**'
      - 'unoplat-code-confluence-ingestion/**'

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: ['unoplat-code-confluence-commons']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ GITHUB.HEAD_REF }}

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: "1.8.3"
      - name: Check poetry version
        run: poetry --version
      - name: Install dependencies
        working-directory: ${{ matrix.path }}
        run: poetry install --no-root
      - name: Build poetry
        working-directory: ${{ matrix.path }}
        run: poetry build -f wheel
        
  test-uv-projects:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ['unoplat-code-confluence-ingestion/code-confluence-flow-bridge']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ GITHUB.HEAD_REF }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Ruff
        uses: astral-sh/ruff-action@v3
        
      - name: Install dependencies and run tests
        working-directory: ${{ matrix.project }}
        env:
          GITHUB_PAT_TOKEN: ${{ github.token }} 
        run: |
          uv sync
          uv run pytest tests/ -v
    
